# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Aliex_UI-1.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtGui import QFont

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 200)

        # Third QTextEdit and its QLabel
        self.label3 = QtWidgets.QLabel(Widget)
        self.label3.setText("NGワード登録（例：時計　パソコン）")
        self.label3.move(30, 20)  # Adjust the position accordingly
        self.textEdit3 = QtWidgets.QTextEdit(Widget)
        self.textEdit3.setGeometry(QtCore.QRect(30, 40, 341, 71))
        
        font = QFont('MS Gothic', 18)
        font1 = QFont('MS Gothic', 12)
        self.label3.setFont(font1)
        self.textEdit3.setFont(font)
        
        self.label_loading = QtWidgets.QLabel(Widget)
        self.label_loading.setGeometry(QtCore.QRect(175, 50, 100, 91))
        self.label_loading.setText("werwer")
        self.label_loading.setObjectName("label_loading")
        
        # QPushButton
        self.startButton = QtWidgets.QPushButton(Widget)
        self.startButton.setGeometry(QtCore.QRect(30, 130, 341, 50))
        self.startButton.setObjectName("startButton")
        self.startButton.setText("開始")
        self.startButton.setStyleSheet('color: white; font-weight: bold; font-size: 20px; background-color: tomato')
	

        